services:
    vcc.betterranks.event:
        class: 'vcc\betterranks\event\listener'
        arguments:
          - '@template'
          - '@config'
          - '@dbal.conn'
          - '@path_helper'
          - '%tables.user_group%'
          - '%tables.users%'
          - '%tables.groups%'
          - '%tables.ranks%'
        tags:
          - { name: 'event.listener' }

    vcc.betterranks.controller.ucp.banners:
        class: 'vcc\betterranks\controller\ucp_banners_controller'
        arguments:
          - '@config'
          - '@template'
          - '@language'
          - '@dbal.conn'
          - '@user'
          - '@request'
          - '%tables.user_group%'
          - '%tables.users%'
          - '%tables.groups%'
          - '%tables.ranks%'